### PR TITLE
CRM-20035 test that communication method is not unset when not passed…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
… in.

Hi @lcdservices I took a look at your PR and I was doubtful whether the problem really is in the form layer, so I tried a quick unit test & I would say it is actually in the BAO::create function instead.

BTW - how can I help you get unit tests happening ?

### CODE REVIEW

**Comment by lcdservices** [comment]
@eileenmcnaughton did you see my comments in the Jira ticket? the reason it happens is because of logic in the BAO::add method -- but I think that logic needs to be preserved to account for the unsetting of values. so although handling it in the form is not ideal, it seems the best way to handle this particular use case. see my comments there for more explanation. note taken about unit tests...

**Comment by vikaskumar14786** [comment]
Hi Brain,
There are some internet issue here.i check it as soon as it resolve.

**Comment by eileenmcnaughton** [comment]
I think "if the array key is not passed, we set an empty value (allow intentional unsetting of existing values)" is bad logic, we should only set an empty value if the key is set & is something that means empty (e.g an empty array) - but I'd settle for if the key is set

**Comment by lcdservices** [comment]
@eileenmcnaughton I agree that is a preferable way to handle it. however, the current behavior seems deeply embedded in the code. I'll dig around a bit to see if there's a clear way to address that. it's not as simply as conditioning on isset (I originally tried that) because the inline edit form and full contact edit form simply don't pass the array element at all if the values are getting unset (maybe a product of how quickform handles checkboxes?). 

FYI, there's a minor style issue with your test script.

**Comment by eileenmcnaughton** [comment]
I would suggest updating the form so that one way or another the form passes it's change to the BAO. Move any hackery to the outer layer

**Comment by lcdservices** [comment]
@eileenmcnaughton this is quite a rabbit hole. The problem is with the construction of the preferred_communication_method checkbox fields/group -- it's odd in it's construction and it's handling. 

When you unset all values for this field and save the form (I'm primarily using the inline edit for testing), the field is completely lost to the form processing. QuickForm's exportValues() doesn't register it, because it's not even present in $this->_submitValues, or even $_REQUEST (?!). The html written to the page is just standard checkbox input fields -- so how it can be missing from the $_REQUEST variable is beyond me. I'm guessing it's passed through a filter somewhere, but I haven't yet found where. But as a result, the contact BAO has existing logic to store an empty value if the field is missing from the form's exportValues (rather than ignore the field, which is what would normally happen). My PR tries to work with that existing workaround.

Taking a step back -- I think the preferred fix is to restructure how the preferred comm field is constructed. And I propose we take the opportunity to change this from a checkbox list to a multi-select field. This is a configurable list, so it could potentially grow in size. A multi-select will handle growth better and trim screen real estate usage. Your thoughts?

**Comment by eileenmcnaughton** [comment]
So, restructure it at the form level or the data level?

**Comment by lcdservices** [comment]
Form. I want to scrap the checkbox list with it's wonky construction and hacky workarounds and replace with a standard multi-select field.

**Comment by eileenmcnaughton** [comment]
ok - I think if you feel it works from UI pov that seems fine to me

**Pull request merged**
